spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: accounts
  profiles:
    active: production

# ACTUATOR INFO
management:
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: "Accounts"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

application:
  allow-get-accounts: ${application.allow-get-accounts}

